spring:
  application:
    name: rag-spring-ai
  docker:
    compose:
      enabled: false
      files: [compose.yaml]
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: password
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when_missing
      chat:
        options:
          model: llama3.2:1b
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
        index-type: HNSW
        distance-type: COSINE_DISTANCE

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    org.springframework.ai.vectorstore: DEBUG